# Generated by Django 2.1.5 on 2019-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Company', '0003_auto_20190122_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
