# Generated by Django 2.1.7 on 2019-03-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_companytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companytype',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CompanyType',
        ),
    ]
