# Generated by Django 2.2.3 on 2019-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_auto_20190328_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nature_of_business',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
