# Generated by Django 2.1.4 on 2019-01-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_auto_20190121_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='updated',
            new_name='updated_date',
        ),
    ]
