# Generated by Django 2.1.7 on 2019-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_auto_20190131_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
    ]
