# Generated by Django 2.1.7 on 2019-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_auto_20190311_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
