# Generated by Django 2.2.4 on 2019-08-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_auto_20190827_1553'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobbenefits',
            table='JobBenefits',
        ),
        migrations.AlterModelTable(
            name='jobcategory',
            table='JobCategory',
        ),
        migrations.AlterModelTable(
            name='jobkeyskills',
            table='JobKeySkills',
        ),
        migrations.AlterModelTable(
            name='jobposistion',
            table='JobPosistion',
        ),
        migrations.AlterModelTable(
            name='jobtype',
            table='JobType',
        ),
    ]
