# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=20)),
                ('address_line_1', models.TextField(max_length=2000)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_line_3', models.TextField(blank=True, null=True)),
                ('post_code', models.TextField(max_length=10)),
                ('county', models.TextField(max_length=20)),
                ('country', models.TextField(max_length=20)),
            ],
        ),
    ]
