# Generated by Django 2.0.3 on 2018-03-14 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=2000)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
