# Generated by Django 2.1.5 on 2019-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Address', '0005_auto_20180611_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
