# Generated by Django 2.1.5 on 2019-01-31 11:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Address', '0006_auto_20190131_1129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresstype',
            table='AddressType',
        ),
    ]
