# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 12:54
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.upload_location),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, upload_to=User.models.upload_location),
        ),
    ]
