# Generated by Django 2.0.3 on 2018-03-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attachment',
        ),
    ]
