# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0004_auto_20171113_2156'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attachment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attachment.Attachment'),
            preserve_default=False,
        ),
    ]
