# Generated by Django 2.0.4 on 2018-04-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0002_attachment_user'),
        ('User', '0002_remove_user_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attachment.Attachment'),
        ),
    ]
