# Generated by Django 2.0.6 on 2018-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20180425_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
