# Generated by Django 2.1.5 on 2019-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('User', '0005_user_alternative_email_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
