# Generated by Django 2.0.3 on 2018-03-14 11:35

import Attachment.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=Attachment.models.upload_location)),
                ('cv', models.FileField(blank=True, upload_to=Attachment.models.upload_location)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
