# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0003_auto_20161231_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
