# Generated by Django 2.1.5 on 2019-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Attachment', '0003_auto_20180425_1553'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='Attachment',
        ),
    ]
