# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0004_auto_20171113_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
