# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0005_attachment_createddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='createdDate',
            new_name='created_date',
        ),
    ]
